# Generated by Django 5.0.6 on 2024-07-09 02:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPurpose',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_purpose',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=100)),
                ('content_author', models.CharField(max_length=100)),
                ('content_author_sub_type', models.CharField(max_length=255)),
                ('content_feature', models.CharField(max_length=255)),
                ('content_sub_feature', models.CharField(max_length=255)),
                ('content_sub_feature_level_1', models.CharField(blank=True, max_length=255, null=True)),
                ('content_sub_feature_level_2', models.CharField(blank=True, max_length=255, null=True)),
                ('content_sub_feature_level_3', models.CharField(blank=True, max_length=255, null=True)),
                ('content_sub_feature_level_4', models.CharField(blank=True, max_length=255, null=True)),
                ('content_sub_feature_level_5', models.CharField(blank=True, max_length=255, null=True)),
                ('content_keywords', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('content_file_path', models.CharField(max_length=255)),
                ('content_file_path_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='ContentLearningModels',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('model_provider', models.CharField(max_length=255)),
                ('model_category', models.CharField(max_length=255)),
                ('model_sub_category', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('model_description', models.TextField(blank=True, null=True)),
                ('model_link', models.URLField(blank=True, max_length=2000, null=True)),
                ('model_keywords', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('model_purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_learning_models', to='migration_content_publisher.apppurpose')),
            ],
            options={
                'db_table': 'content_learning_models',
            },
        ),
        migrations.CreateModel(
            name='LearningCategory',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('category_purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_categories', to='migration_content_publisher.apppurpose')),
            ],
            options={
                'db_table': 'learning_category',
            },
        ),
    ]
